main: de.timesnake.game.endgame.main.GameEndGame
version: 1.1
name: game-endgame
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  endgame:
  eg:
  loc:
  location:
  pos:
  position:
  locshow:
  tria:
  triangular:
  stronghold:
