main: de.timesnake.game.endgame.main.GameEndGame
version: 1.2.2
name: game-endgame
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  endgame:
    aliases:
      - eg
  loc:
    aliases:
      - location
      - pos
      - postion
  locshow:

  triangular:
    aliases:
      - tria
      - stronghold
